version: '3.8'

services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./master_frontend
    ports:
     - "80:80"
     - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/sites-available/default
      - /var/certs/etc-letsencrypt:/etc/letsencrypt
    depends_on:
      - api
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    build:
      dockerfile: Dockerfile
      context: ./node-postgres
    ports:
     - '8000:8000'
    restart: always
    volumes:
      - ./node_postgres:/node_postgres
      - /node_postgres/node_modules