version: '3.8'

services:
  nginx:
    depends_on:
      - client
      - api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
     - "3050:80"
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./master_frontend
    volumes:
     - /app/node_modules
     - ./master_frontend:/app
  api:
    build:
      dockerfile: Dockerfile
      context: "./node-postgres"
    volumes:
      - /app/node_modules
      - ./node_postgres:/app